modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20More%20Zombie%20Villagers"
logoFile="icon.png"

[[mods]]
modId="morezombievillagers"
version="3.3"
displayName="More Zombie Villagers"
displayURL="https://curseforge.com/minecraft/mc-mods/more-zombie-villagers"
authors="Rick South"
description='''Allows modifying the default chance a zombie spawn is of the villager variant.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.morezombievillagers]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"